external:
  channel:
    connection:
      timeout: 1000
    request:
      timeout: 3000

  api:
    url: http://localhost:9090

logging:
  config: classpath:log4j2.xml

server:
  port: 8080
  
spring:
  jackson:
    date-format: "YYYY-MM-dd"
    serialization:
      write_dates_as_timestamps: false